### ISSUE TITLE
Unexpected replacements for "^", "$", ""

### ISSUE THREAD

**Issue by kaushalmodi** [nitely/nim-regex#29] opened 2018-10-11 10:49 UTC
See https://github.com/nim-lang/Nim/issues/9306.

```nim
import regex
echo replace("bar", re"^", "foo")
echo replace("foo", re"$", "bar")
echo replace("foo", re"", "-")
```

produces:

```
foobfooafoor # expected: foobar
fobarbarbarfoo # expected: foobar
-f-o-o # expected: -f-o-o-
```

**Comment by timotheecour** [comment] 2018-10-11 19:11
as mentioned in https://github.com/nim-lang/Nim/issues/9306#issue-369016855 what nre does here seems correct:

Using nre:
```
import nre
echo replace("bar", re"^", "foo")
echo replace("foo", re"$", "bar")
echo replace("foo", re"", "-")
produces:

foobar
foobar
-f-o-o-
```

**Comment by nitely** [comment] 2018-10-11 20:05
I think this a duplicate of https://github.com/nitely/nim-regex/issues/13. I'll try to fix it (again) this weekend. IIRC, it's not as easy as implementing the nre version of this function, there is some issue in how empty matches are handled.

**Closed** 2020-05-07 13:47 UTC

**Comment by kaushalmodi** [comment] 2020-05-07 13:50
Thank you!!
